/**
 * Comprehensive AI Tools Data
 *
 * Complete catalog of all 253 AI tools organized by category.
 * This data powers the AI Tools Documentation page.
 */

export interface AIToolDoc {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  examples: string[];
  keywords: string[];
  isPrimary?: boolean;
  isAdvanced?: boolean;
}

export interface ToolCategoryDoc {
  id: string;
  displayName: string;
  description: string;
  icon: string;
  sortOrder: number;
}

export const toolCategories: ToolCategoryDoc[] = [
  {
    id: 'property_search',
    displayName: 'Property Search',
    description: 'Find and filter properties',
    icon: 'Search',
    sortOrder: 1,
  },
  {
    id: 'deal_analysis',
    displayName: 'Deal Analysis',
    description: 'Analyze deals and calculate metrics',
    icon: 'Calculator',
    sortOrder: 2,
  },
  {
    id: 'buyer_management',
    displayName: 'Buyer Management',
    description: 'Find and manage cash buyers',
    icon: 'Users',
    sortOrder: 3,
  },
  {
    id: 'market_analysis',
    displayName: 'Market Analysis',
    description: 'Research markets and trends',
    icon: 'TrendingUp',
    sortOrder: 4,
  },
  {
    id: 'valuation',
    displayName: 'Valuation',
    description: 'Property valuations and comps',
    icon: 'DollarSign',
    sortOrder: 5,
  },
  {
    id: 'communication',
    displayName: 'Communication',
    description: 'Outreach and messaging',
    icon: 'MessageSquare',
    sortOrder: 6,
  },
  {
    id: 'deal_pipeline',
    displayName: 'Deal Pipeline',
    description: 'Manage deals through pipeline',
    icon: 'GitBranch',
    sortOrder: 7,
  },
  {
    id: 'skip_tracing',
    displayName: 'Skip Tracing',
    description: 'Find owner contact information',
    icon: 'Phone',
    sortOrder: 8,
  },
  {
    id: 'documents',
    displayName: 'Documents',
    description: 'Generate documents and reports',
    icon: 'FileText',
    sortOrder: 9,
  },
  {
    id: 'permits',
    displayName: 'Permits & Compliance',
    description: 'Permit history and analysis',
    icon: 'FileText',
    sortOrder: 10,
  },
  {
    id: 'contractors',
    displayName: 'Contractors',
    description: 'Find and compare contractors',
    icon: 'Hammer',
    sortOrder: 11,
  },
  {
    id: 'predictive',
    displayName: 'Predictive AI',
    description: 'AI-powered predictions and scoring',
    icon: 'Sparkles',
    sortOrder: 12,
  },
  {
    id: 'crm',
    displayName: 'CRM & Lists',
    description: 'Lead management and organization',
    icon: 'List',
    sortOrder: 13,
  },
  {
    id: 'automation',
    displayName: 'Automation',
    description: 'Workflow automation and alerts',
    icon: 'Zap',
    sortOrder: 14,
  },
  {
    id: 'map_tools',
    displayName: 'Map Tools',
    description: 'Geographic analysis and mapping',
    icon: 'MapPin',
    sortOrder: 15,
  },
  {
    id: 'intelligence',
    displayName: 'Market Intelligence',
    description: 'Competitive and market intelligence',
    icon: 'Target',
    sortOrder: 16,
  },
  {
    id: 'batch_operations',
    displayName: 'Batch Operations',
    description: 'Bulk operations on multiple items',
    icon: 'Users',
    sortOrder: 17,
  },
  {
    id: 'reporting',
    displayName: 'Analytics & Reporting',
    description: 'Dashboard analytics and insights',
    icon: 'BarChart3',
    sortOrder: 18,
  },
  {
    id: 'portfolio',
    displayName: 'Portfolio Management',
    description: 'Manage your property portfolio',
    icon: 'Home',
    sortOrder: 19,
  },
  {
    id: 'integrations',
    displayName: 'Integrations',
    description: 'Connect to external systems',
    icon: 'Wrench',
    sortOrder: 20,
  },
  {
    id: 'verticals',
    displayName: 'Business Verticals',
    description: 'Vertical-specific features',
    icon: 'Settings',
    sortOrder: 21,
  },
];

export const allAITools: AIToolDoc[] = [
  // ==========================================
  // PROPERTY SEARCH (37 tools)
  // ==========================================
  {
    id: 'property_search.search',
    name: 'Natural Language Search',
    description: 'Search for properties using plain English descriptions',
    category: 'property_search',
    icon: 'Search',
    examples: [
      'Find 3 bed houses in Tampa with tired landlords under $200k',
      'High equity absentee owners in 33607',
      'Free and clear properties near downtown Orlando',
    ],
    keywords: ['search', 'find', 'properties', 'filter'],
    isPrimary: true,
  },
  {
    id: 'property_search.get_details',
    name: 'Property Details',
    description: 'Get detailed information about a specific property',
    category: 'property_search',
    icon: 'Home',
    examples: ['Tell me about 123 Main St, Tampa FL', 'What can you tell me about this property?'],
    keywords: ['details', 'info', 'property'],
    isPrimary: false,
  },
  {
    id: 'search.by_description',
    name: 'Conversational Search',
    description: 'Search using natural language description',
    category: 'property_search',
    icon: 'MessageSquare',
    examples: [
      'I need fix and flip opportunities under $150k',
      'Find me wholesale deals that I can assign quickly',
    ],
    keywords: ['search', 'natural language', 'conversational'],
    isPrimary: false,
  },
  {
    id: 'search.similar_to_deal',
    name: 'Find Similar Properties',
    description: 'Find properties like your successful deals',
    category: 'property_search',
    icon: 'Target',
    examples: ['Find properties similar to my best deal', 'Show me more properties like this one'],
    keywords: ['similar', 'like', 'match'],
    isPrimary: false,
  },
  {
    id: 'search.execute_filter',
    name: 'Execute Filter',
    description: 'Execute a saved search filter',
    category: 'property_search',
    icon: 'Filter',
    examples: ['Run my hot leads filter', 'Execute saved search Tampa Absentee'],
    keywords: ['filter', 'execute', 'run', 'saved search'],
  },
  {
    id: 'search.save_filter',
    name: 'Save Search',
    description: 'Save current search as a reusable filter',
    category: 'property_search',
    icon: 'Bookmark',
    examples: ['Save this search as "Tampa Hot Leads"'],
    keywords: ['save', 'filter', 'bookmark'],
  },
  {
    id: 'search.recent',
    name: 'Recent Searches',
    description: 'View recent search history',
    category: 'property_search',
    icon: 'Clock',
    examples: ['Show my recent searches'],
    keywords: ['recent', 'history', 'searches'],
  },
  {
    id: 'search.refine',
    name: 'Refine Search',
    description: 'Refine search based on natural language',
    category: 'property_search',
    icon: 'Filter',
    examples: ['Make this search more specific', 'Narrow down these results'],
    keywords: ['refine', 'narrow', 'filter'],
  },
  {
    id: 'search.compare',
    name: 'Compare Search Results',
    description: 'Compare two search result sets',
    category: 'property_search',
    icon: 'GitCompare',
    examples: ['Compare these two searches'],
    keywords: ['compare', 'results'],
  },
  {
    id: 'search.export',
    name: 'Export Search Results',
    description: 'Export search results to CSV/JSON',
    category: 'property_search',
    icon: 'Download',
    examples: ['Export these results to CSV'],
    keywords: ['export', 'download', 'csv'],
  },
  {
    id: 'search.schedule',
    name: 'Schedule Search',
    description: 'Schedule a recurring search',
    category: 'property_search',
    icon: 'Calendar',
    examples: ['Run this search daily and email me results'],
    keywords: ['schedule', 'recurring', 'automated'],
  },
  {
    id: 'search.suggestions',
    name: 'Search Suggestions',
    description: 'Get AI-based search suggestions',
    category: 'property_search',
    icon: 'Sparkles',
    examples: ['Suggest searches for me', 'What should I search for?'],
    keywords: ['suggestions', 'recommend', 'ideas'],
  },
  {
    id: 'search.analyze',
    name: 'Analyze Search Performance',
    description: 'Analyze search-to-deal conversion',
    category: 'property_search',
    icon: 'BarChart3',
    examples: ['Which searches convert best?'],
    keywords: ['analyze', 'performance', 'conversion'],
    isAdvanced: true,
  },
  {
    id: 'search.buyer_property_match',
    name: 'Match Buyer to Properties',
    description: 'Find properties matching buyer criteria',
    category: 'property_search',
    icon: 'UserSearch',
    examples: ['Find properties for this buyer'],
    keywords: ['buyer', 'match', 'properties'],
  },
  {
    id: 'search.permit_pattern_match',
    name: 'Permit Pattern Search',
    description: 'Find properties with specific permit patterns',
    category: 'property_search',
    icon: 'FileText',
    examples: ['Find properties with stalled permits'],
    keywords: ['permits', 'pattern', 'search'],
  },
  {
    id: 'map.draw_search_area',
    name: 'Draw Search Area',
    description: 'Define geographic search area on map',
    category: 'property_search',
    icon: 'MapPin',
    examples: ['Search within 2 miles of downtown Tampa'],
    keywords: ['map', 'area', 'geographic'],
  },
  {
    id: 'map.show_commute_time',
    name: 'Commute Time Analysis',
    description: 'Show areas by drive time',
    category: 'property_search',
    icon: 'MapPin',
    examples: ['Show properties within 20 minutes of downtown'],
    keywords: ['commute', 'drive time', 'distance'],
  },

  // Filter Tools
  {
    id: 'filter.suggest',
    name: 'Suggest Filters',
    description: 'Get filter recommendations based on goals',
    category: 'property_search',
    icon: 'Sparkles',
    examples: ['What filters should I use for motivated sellers?'],
    keywords: ['suggest', 'recommend', 'filters'],
  },
  {
    id: 'filter.explain',
    name: 'Explain Filter',
    description: 'Learn what a filter does and when to use it',
    category: 'property_search',
    icon: 'HelpCircle',
    examples: ['What is a tired landlord?', 'Explain the underwater landlord filter'],
    keywords: ['explain', 'filter', 'definition'],
    isPrimary: false,
  },
  {
    id: 'filter.optimize',
    name: 'Optimize Filters',
    description: 'Analyze and improve filter combinations',
    category: 'property_search',
    icon: 'Zap',
    examples: ['Optimize my filter set'],
    keywords: ['optimize', 'improve', 'filters'],
    isAdvanced: true,
  },
  {
    id: 'filter.create',
    name: 'Create Custom Filter',
    description: 'Create filter from natural language',
    category: 'property_search',
    icon: 'Plus',
    examples: ['Create a filter for properties likely to sell'],
    keywords: ['create', 'custom', 'filter'],
  },
  {
    id: 'filter.compare',
    name: 'Compare Filters',
    description: 'Compare two filter sets',
    category: 'property_search',
    icon: 'GitCompare',
    examples: ['Compare these two filter sets'],
    keywords: ['compare', 'filters'],
  },
  {
    id: 'filter.performance',
    name: 'Filter Performance',
    description: 'Track filter conversion rates',
    category: 'property_search',
    icon: 'BarChart3',
    examples: ['Which filters convert best?'],
    keywords: ['performance', 'conversion', 'filters'],
    isAdvanced: true,
  },
  {
    id: 'filter.refine',
    name: 'Refine Filters',
    description: 'Suggest filter adjustments based on results',
    category: 'property_search',
    icon: 'Settings',
    examples: ['Refine my filters to get better results'],
    keywords: ['refine', 'adjust', 'improve'],
  },
  {
    id: 'filter.export',
    name: 'Export Filter',
    description: 'Export filter as shareable format',
    category: 'property_search',
    icon: 'Download',
    examples: ['Export this filter definition'],
    keywords: ['export', 'share', 'filter'],
  },
  {
    id: 'filter.import',
    name: 'Import Filter',
    description: 'Import filter from definition',
    category: 'property_search',
    icon: 'Upload',
    examples: ['Import filter from file'],
    keywords: ['import', 'load', 'filter'],
  },
  {
    id: 'filter.recommendations',
    name: 'Filter Recommendations',
    description: 'Get recommendations based on success patterns',
    category: 'property_search',
    icon: 'Star',
    examples: ['Recommend filters based on my closed deals'],
    keywords: ['recommend', 'suggestions', 'filters'],
  },
  {
    id: 'filter.validate',
    name: 'Validate Filter',
    description: 'Check filter for logical errors',
    category: 'property_search',
    icon: 'CheckCircle',
    examples: ['Validate this filter'],
    keywords: ['validate', 'check', 'filter'],
  },

  // Property Detail Tools
  {
    id: 'property.valuation',
    name: 'Property Valuation',
    description: 'Get AI-powered property valuation',
    category: 'valuation',
    icon: 'DollarSign',
    examples: ["What's this property worth?", 'Estimate the ARV'],
    keywords: ['valuation', 'arv', 'worth'],
    isPrimary: true,
  },
  {
    id: 'property.comps',
    name: 'Comparable Sales',
    description: 'Find recent comparable sales',
    category: 'valuation',
    icon: 'Scale',
    examples: ['Pull comps for this property', 'Find similar sales nearby'],
    keywords: ['comps', 'comparables', 'sales'],
    isPrimary: true,
  },
  {
    id: 'property.repairs',
    name: 'Repair Estimate',
    description: 'Estimate repair costs',
    category: 'valuation',
    icon: 'Hammer',
    examples: ['Estimate repair costs for this property'],
    keywords: ['repairs', 'renovation', 'costs'],
  },
  {
    id: 'property.rental',
    name: 'Rental Analysis',
    description: 'Assess rental income potential',
    category: 'deal_analysis',
    icon: 'DollarSign',
    examples: ['What could this rent for?', 'Calculate the cap rate'],
    keywords: ['rental', 'income', 'cap rate'],
    isPrimary: true,
  },
  {
    id: 'property.neighborhood',
    name: 'Neighborhood Insights',
    description: 'Analyze surrounding area and neighborhood',
    category: 'market_analysis',
    icon: 'MapPin',
    examples: ['Tell me about the neighborhood', 'Is this a good area for rentals?'],
    keywords: ['neighborhood', 'area', 'location'],
  },
  {
    id: 'property.issues',
    name: 'Property Red Flags',
    description: 'Identify potential issues and red flags',
    category: 'deal_analysis',
    icon: 'AlertTriangle',
    examples: ['Check for red flags', 'Are there any liens?'],
    keywords: ['issues', 'red flags', 'liens', 'problems'],
  },
  {
    id: 'property.motivation',
    name: 'Seller Motivation Score',
    description: 'Calculate seller motivation score',
    category: 'deal_analysis',
    icon: 'Target',
    examples: ["What's the motivation score?", 'Is this seller motivated?'],
    keywords: ['motivation', 'seller', 'score'],
  },
  {
    id: 'property.summary',
    name: 'Property Summary',
    description: 'Generate AI-written property description',
    category: 'documents',
    icon: 'FileText',
    examples: ['Summarize this property'],
    keywords: ['summary', 'description', 'write'],
  },
  {
    id: 'property.deal_potential',
    name: 'Deal Potential',
    description: 'Analyze potential profit margins',
    category: 'deal_analysis',
    icon: 'TrendingUp',
    examples: ["What's the profit potential?"],
    keywords: ['potential', 'profit', 'margins'],
  },
  {
    id: 'property.ownership',
    name: 'Ownership History',
    description: 'View ownership timeline',
    category: 'property_search',
    icon: 'Clock',
    examples: ['Show ownership history'],
    keywords: ['ownership', 'history', 'timeline'],
  },
  {
    id: 'property.time_on_market',
    name: 'Predict Time on Market',
    description: 'Predict days to sell',
    category: 'predictive',
    icon: 'Clock',
    examples: ['How long will this take to sell?'],
    keywords: ['time', 'market', 'predict'],
  },
  {
    id: 'property.portfolio_compare',
    name: 'Compare to Portfolio',
    description: 'Compare to your past deals',
    category: 'portfolio',
    icon: 'GitCompare',
    examples: ['Compare to my portfolio'],
    keywords: ['compare', 'portfolio', 'past deals'],
  },
  {
    id: 'property.offer_price',
    name: 'Generate Offer Price',
    description: 'Calculate optimal offer price',
    category: 'deal_analysis',
    icon: 'DollarSign',
    examples: ['What should I offer?'],
    keywords: ['offer', 'price', 'calculate'],
    isPrimary: true,
  },

  // ==========================================
  // DEAL ANALYSIS (14 tools)
  // ==========================================
  {
    id: 'deal_analysis.analyze',
    name: 'Deal Analysis',
    description: 'Comprehensive deal analysis with ARV, MAO, and profit calculations',
    category: 'deal_analysis',
    icon: 'Calculator',
    examples: ['Analyze this deal', 'Is this a good wholesale deal?'],
    keywords: ['analyze', 'deal', 'arv', 'mao'],
    isPrimary: true,
  },
  {
    id: 'deal_analysis.calculate_mao',
    name: 'Calculate MAO',
    description: 'Calculate Maximum Allowable Offer',
    category: 'deal_analysis',
    icon: 'Calculator',
    examples: ["What's the MAO?", 'Calculate MAO with $30k repairs'],
    keywords: ['mao', 'maximum', 'allowable', 'offer'],
  },
  {
    id: 'deal_analysis.score',
    name: 'Score Deal',
    description: 'Get AI-powered deal score',
    category: 'deal_analysis',
    icon: 'Star',
    examples: ['Score this deal'],
    keywords: ['score', 'rating', 'evaluate'],
  },
  {
    id: 'predict.seller_motivation',
    name: 'Predict Seller Motivation',
    description: 'Predict seller motivation score',
    category: 'predictive',
    icon: 'Target',
    examples: ['Is this seller motivated?', "What's the motivation score?"],
    keywords: ['motivation', 'seller', 'predict'],
  },
  {
    id: 'predict.deal_success',
    name: 'Deal Success Prediction',
    description: 'Predict likelihood of closing',
    category: 'predictive',
    icon: 'Target',
    examples: ['Will this deal close?', 'What are my chances?'],
    keywords: ['predict', 'success', 'close'],
    isAdvanced: true,
  },
  {
    id: 'predict.optimal_offer',
    name: 'Optimal Offer Suggestion',
    description: 'Get AI-recommended offer strategy',
    category: 'deal_analysis',
    icon: 'DollarSign',
    examples: ['What should I offer?', 'Suggest an offer strategy'],
    keywords: ['offer', 'optimal', 'suggest'],
  },
  {
    id: 'predict.market_timing',
    name: 'Market Timing Prediction',
    description: 'Predict best timing for market entry/exit',
    category: 'predictive',
    icon: 'Clock',
    examples: ['Should I buy now or wait?', 'Is this a good time to buy?'],
    keywords: ['timing', 'market', 'predict'],
  },
  {
    id: 'predict.comp_trends',
    name: 'Comp Trends Prediction',
    description: 'Predict future comparable sale trends',
    category: 'predictive',
    icon: 'TrendingUp',
    examples: ['How will comps trend in this area?'],
    keywords: ['comps', 'trends', 'predict'],
    isAdvanced: true,
  },
  {
    id: 'predict.property_demand',
    name: 'Property Demand Prediction',
    description: 'Predict demand for property type',
    category: 'predictive',
    icon: 'TrendingUp',
    examples: ['Is there demand for this type of property?'],
    keywords: ['demand', 'predict', 'market'],
  },
  {
    id: 'predict.classify_owner',
    name: 'Classify Owner Type',
    description: 'Identify owner type and characteristics',
    category: 'deal_analysis',
    icon: 'UserCheck',
    examples: ['What type of owner is this?'],
    keywords: ['owner', 'classify', 'type'],
    isAdvanced: true,
  },
  {
    id: 'permit.analyze_patterns',
    name: 'Permit Pattern Analysis',
    description: 'Identify motivation signals from permits',
    category: 'permits',
    icon: 'Activity',
    examples: ['Analyze permit patterns for motivation'],
    keywords: ['permits', 'patterns', 'motivation'],
    isAdvanced: true,
  },

  // ==========================================
  // BUYER MANAGEMENT (13 tools)
  // ==========================================
  {
    id: 'buyer_management.match_buyers_to_property',
    name: 'Match Buyers to Property',
    description: 'Find buyers matching property criteria',
    category: 'buyer_management',
    icon: 'UserSearch',
    examples: ['Find buyers for this property', "Who's buying in this area?"],
    keywords: ['buyers', 'match', 'find'],
    isPrimary: true,
  },
  {
    id: 'buyer_management.search_buyers',
    name: 'Search Buyers',
    description: 'Search buyer database',
    category: 'buyer_management',
    icon: 'Users',
    examples: ['Show buyers interested in Tampa duplexes'],
    keywords: ['search', 'buyers', 'database'],
  },
  {
    id: 'buyer_management.get_buyer_insights',
    name: 'Buyer Insights',
    description: 'Get analytics on a buyer',
    category: 'buyer_management',
    icon: 'BarChart3',
    examples: ["Tell me about this buyer's purchase history"],
    keywords: ['insights', 'buyer', 'analytics'],
    isAdvanced: true,
  },
  {
    id: 'buyer_management.analyze_buyer_activity',
    name: 'Buyer Activity Analysis',
    description: 'Analyze buyer engagement patterns',
    category: 'buyer_management',
    icon: 'Activity',
    examples: ['Which buyers are most active?'],
    keywords: ['activity', 'buyers', 'engagement'],
  },
  {
    id: 'buyer.suggest_outreach',
    name: 'Buyer Outreach Suggestions',
    description: 'Get buyer contact recommendations',
    category: 'buyer_management',
    icon: 'Target',
    examples: ['Which buyers should I contact?'],
    keywords: ['outreach', 'buyers', 'contact'],
  },
  {
    id: 'buyer.compare',
    name: 'Compare Buyers',
    description: 'Compare multiple buyers',
    category: 'buyer_management',
    icon: 'GitCompare',
    examples: ['Compare these buyers for this deal'],
    keywords: ['compare', 'buyers'],
  },
  {
    id: 'buyer.predict_behavior',
    name: 'Predict Buyer Behavior',
    description: 'Predict buyer response',
    category: 'predictive',
    icon: 'Target',
    examples: ['Will this buyer be interested?'],
    keywords: ['predict', 'buyer', 'behavior'],
    isAdvanced: true,
  },
  {
    id: 'buyer.segment',
    name: 'Segment Buyers',
    description: 'Group buyers by criteria',
    category: 'buyer_management',
    icon: 'Users',
    examples: ['Segment buyers by investment strategy'],
    keywords: ['segment', 'group', 'buyers'],
  },
  {
    id: 'buyer.identify_gaps',
    name: 'Identify Buyer Gaps',
    description: 'Find missing buyer types in network',
    category: 'buyer_management',
    icon: 'AlertTriangle',
    examples: ['What types of buyers am I missing?'],
    keywords: ['gaps', 'missing', 'buyers'],
    isAdvanced: true,
  },
  {
    id: 'buyer.generate_report',
    name: 'Generate Buyer Report',
    description: 'Create buyer summary report',
    category: 'buyer_management',
    icon: 'FileText',
    examples: ['Generate a buyer report'],
    keywords: ['report', 'buyer', 'summary'],
  },
  {
    id: 'buyer.score_fit',
    name: 'Buyer Match Score',
    description: 'Calculate buyer-property fit score',
    category: 'buyer_management',
    icon: 'Target',
    examples: ['How good of a match is this buyer?'],
    keywords: ['score', 'match', 'fit'],
    isAdvanced: true,
  },
  {
    id: 'buyer.track_preference_changes',
    name: 'Track Buyer Preferences',
    description: 'Monitor buyer preference changes',
    category: 'buyer_management',
    icon: 'TrendingUp',
    examples: ['Have this buyer preferences changed?'],
    keywords: ['track', 'preferences', 'changes'],
    isAdvanced: true,
  },
  {
    id: 'buyer.recommend_actions',
    name: 'Recommend Buyer Actions',
    description: 'Suggest next actions for buyers',
    category: 'buyer_management',
    icon: 'Sparkles',
    examples: ['What should I do with this buyer?'],
    keywords: ['recommend', 'actions', 'buyer'],
  },

  // ==========================================
  // MARKET ANALYSIS (24 tools)
  // ==========================================
  {
    id: 'market.get_trends',
    name: 'Market Overview',
    description: 'Get market statistics and trends',
    category: 'market_analysis',
    icon: 'TrendingUp',
    examples: ["How's the Tampa market doing?", "What's the median price in 33607?"],
    keywords: ['market', 'trends', 'statistics'],
    isPrimary: true,
  },
  {
    id: 'market_velocity.get_velocity',
    name: 'Market Velocity Index',
    description: 'Check market movement speed',
    category: 'market_analysis',
    icon: 'Gauge',
    examples: ['How fast is the Tampa market moving?'],
    keywords: ['velocity', 'speed', 'market'],
  },
  {
    id: 'market.compare_markets',
    name: 'Compare Markets',
    description: 'Side-by-side market comparison',
    category: 'market_analysis',
    icon: 'GitCompare',
    examples: ['Compare Tampa and Orlando markets'],
    keywords: ['compare', 'markets'],
  },
  {
    id: 'market_analysis.forecast',
    name: 'Price Forecast',
    description: 'Predict future property prices',
    category: 'market_analysis',
    icon: 'TrendingUp',
    examples: ['What will prices do in the next 6 months?'],
    keywords: ['forecast', 'predict', 'prices'],
  },
  {
    id: 'market_analysis.trends',
    name: 'Market Trend Analysis',
    description: 'Analyze market trends and momentum',
    category: 'market_analysis',
    icon: 'TrendingUp',
    examples: ['Analyze Tampa market trends'],
    keywords: ['trends', 'analysis', 'market'],
  },
  {
    id: 'market_analysis.compare',
    name: 'Multi-Market Comparison',
    description: 'Compare multiple markets',
    category: 'market_analysis',
    icon: 'GitCompare',
    examples: ['Compare 5 Florida markets'],
    keywords: ['compare', 'markets', 'multiple'],
  },
  {
    id: 'market_analysis.seasonality',
    name: 'Seasonality Analysis',
    description: 'Analyze seasonal patterns',
    category: 'market_analysis',
    icon: 'Calendar',
    examples: ['How does the market perform seasonally?'],
    keywords: ['seasonality', 'patterns', 'seasonal'],
  },
  {
    id: 'market_analysis.supply_demand',
    name: 'Supply/Demand Analysis',
    description: 'Analyze market dynamics',
    category: 'market_analysis',
    icon: 'Activity',
    examples: ['Analyze supply and demand in Tampa'],
    keywords: ['supply', 'demand', 'dynamics'],
  },
  {
    id: 'market_analysis.economic',
    name: 'Economic Indicators',
    description: 'Analyze economic factors',
    category: 'market_analysis',
    icon: 'DollarSign',
    examples: ['Show economic indicators for this market'],
    keywords: ['economic', 'indicators', 'factors'],
    isAdvanced: true,
  },
  {
    id: 'market_analysis.roi',
    name: 'Investment ROI Calculator',
    description: 'Calculate investment returns',
    category: 'market_analysis',
    icon: 'Calculator',
    examples: ["What's my expected ROI?"],
    keywords: ['roi', 'returns', 'investment'],
  },
  {
    id: 'market_analysis.neighborhood',
    name: 'Neighborhood Scoring',
    description: 'Score neighborhood quality',
    category: 'market_analysis',
    icon: 'Star',
    examples: ['Score this neighborhood'],
    keywords: ['neighborhood', 'score', 'quality'],
  },
  {
    id: 'market_analysis.rental',
    name: 'Rental Market Analysis',
    description: 'Analyze rental market conditions',
    category: 'market_analysis',
    icon: 'Home',
    examples: ["How's the rental market in this area?"],
    keywords: ['rental', 'market', 'analysis'],
  },
  {
    id: 'market_analysis.timing',
    name: 'Market Timing Indicator',
    description: 'Get market timing signals',
    category: 'market_analysis',
    icon: 'Clock',
    examples: ['Is now a good time to buy in Tampa?'],
    keywords: ['timing', 'signals', 'market'],
  },

  // Heat Mapping Tools
  {
    id: 'heat_mapping.analyze_area',
    name: 'Analyze Area',
    description: 'Analyze geographic area for opportunities',
    category: 'map_tools',
    icon: 'Map',
    examples: ['Analyze the downtown Tampa area'],
    keywords: ['analyze', 'area', 'geographic'],
  },
  {
    id: 'heat_mapping.competition_analysis',
    name: 'Competition Analysis',
    description: 'Analyze competition levels',
    category: 'intelligence',
    icon: 'Users',
    examples: ['How much competition is in this area?'],
    keywords: ['competition', 'analysis'],
  },
  {
    id: 'heat_mapping.detect_opportunities',
    name: 'Detect Opportunity Zones',
    description: 'Identify high-opportunity areas',
    category: 'market_analysis',
    icon: 'Target',
    examples: ['Where are the best opportunities in Tampa?'],
    keywords: ['opportunities', 'zones', 'detect'],
  },
  {
    id: 'heat_mapping.price_trends',
    name: 'Price Trend Mapping',
    description: 'Analyze price trends by area',
    category: 'market_analysis',
    icon: 'TrendingUp',
    examples: ['Show price trends on the map'],
    keywords: ['price', 'trends', 'mapping'],
  },
  {
    id: 'heat_mapping.distress_indicator',
    name: 'Distress Indicator',
    description: 'Identify distressed property concentrations',
    category: 'market_analysis',
    icon: 'AlertTriangle',
    examples: ['Show distressed areas'],
    keywords: ['distress', 'distressed', 'properties'],
  },
  {
    id: 'heat_mapping.equity_analysis',
    name: 'Equity Heat Map',
    description: 'Analyze equity levels by area',
    category: 'market_analysis',
    icon: 'DollarSign',
    examples: ['Show high equity areas'],
    keywords: ['equity', 'heat map', 'analysis'],
  },
  {
    id: 'heat_mapping.absentee_owners',
    name: 'Absentee Owner Map',
    description: 'Identify absentee owner concentrations',
    category: 'market_analysis',
    icon: 'MapPin',
    examples: ['Show absentee owner hot spots'],
    keywords: ['absentee', 'owners', 'map'],
  },
  {
    id: 'heat_mapping.rental_yield',
    name: 'Rental Yield Analysis',
    description: 'Calculate rental yields by area',
    category: 'market_analysis',
    icon: 'Home',
    examples: ['Show rental yield map'],
    keywords: ['rental', 'yield', 'analysis'],
  },
  {
    id: 'heat_mapping.inventory',
    name: 'Inventory Analysis',
    description: 'Analyze current inventory levels',
    category: 'market_analysis',
    icon: 'List',
    examples: ['Show inventory by area'],
    keywords: ['inventory', 'levels', 'analysis'],
  },
  {
    id: 'heat_mapping.days_on_market',
    name: 'Days on Market Analysis',
    description: 'Analyze average days on market',
    category: 'market_analysis',
    icon: 'Clock',
    examples: ['Show days on market by area'],
    keywords: ['days', 'market', 'analysis'],
  },
  {
    id: 'heat_mapping.flip_potential',
    name: 'Flip Potential Map',
    description: 'Analyze flip potential by area',
    category: 'market_analysis',
    icon: 'Home',
    examples: ['Show best areas for flipping'],
    keywords: ['flip', 'potential', 'map'],
  },

  // ==========================================
  // COMMUNICATION & OUTREACH (16 tools)
  // ==========================================
  {
    id: 'comms.generate_sms_template',
    name: 'Generate SMS',
    description: 'Create personalized text messages',
    category: 'communication',
    icon: 'MessageSquare',
    examples: ['Write an SMS for this absentee owner'],
    keywords: ['sms', 'text', 'message'],
    isPrimary: true,
  },
  {
    id: 'comms.generate_email_sequence',
    name: 'Generate Email Sequence',
    description: 'Create email drip campaigns',
    category: 'communication',
    icon: 'Mail',
    examples: ['Create an email sequence for this seller'],
    keywords: ['email', 'sequence', 'drip'],
  },
  {
    id: 'comms.generate_talking_points',
    name: 'Generate Talking Points',
    description: 'Create call scripts and talking points',
    category: 'communication',
    icon: 'Phone',
    examples: ['Give me talking points for this call'],
    keywords: ['talking points', 'script', 'call'],
  },
  {
    id: 'notification.send_sms',
    name: 'Send SMS',
    description: 'Send text message directly',
    category: 'communication',
    icon: 'MessageSquare',
    examples: ['Send an SMS to this owner'],
    keywords: ['send', 'sms', 'text'],
  },
  {
    id: 'notification.send_email',
    name: 'Send Email',
    description: 'Send email directly',
    category: 'communication',
    icon: 'Mail',
    examples: ['Email this owner with an offer'],
    keywords: ['send', 'email'],
  },
  {
    id: 'notification.schedule_call',
    name: 'Schedule Call',
    description: 'Schedule call reminder',
    category: 'communication',
    icon: 'Phone',
    examples: ['Schedule a call with this owner'],
    keywords: ['schedule', 'call', 'reminder'],
  },
  {
    id: 'notification.send_batch_sms',
    name: 'Send Batch SMS',
    description: 'Send SMS to multiple recipients',
    category: 'communication',
    icon: 'Users',
    examples: ['Send SMS to all these owners'],
    keywords: ['batch', 'sms', 'multiple'],
  },
  {
    id: 'notification.send_batch_email',
    name: 'Send Batch Email',
    description: 'Send email to multiple recipients',
    category: 'communication',
    icon: 'Users',
    examples: ['Email all these owners'],
    keywords: ['batch', 'email', 'multiple'],
  },
  {
    id: 'notification.create_drip_campaign',
    name: 'Create Drip Campaign',
    description: 'Set up automated follow-up sequence',
    category: 'automation',
    icon: 'Zap',
    examples: ['Set up a 5-email drip campaign'],
    keywords: ['drip', 'campaign', 'automated'],
  },
  {
    id: 'notification.get_templates',
    name: 'Get Message Templates',
    description: 'View available templates',
    category: 'communication',
    icon: 'FileText',
    examples: ['Show message templates'],
    keywords: ['templates', 'messages'],
  },
  {
    id: 'notification.create_template',
    name: 'Create Message Template',
    description: 'Create new message template',
    category: 'communication',
    icon: 'Plus',
    examples: ['Create a new SMS template'],
    keywords: ['create', 'template'],
  },
  {
    id: 'notification.track_engagement',
    name: 'Track Engagement',
    description: 'Get engagement metrics',
    category: 'communication',
    icon: 'BarChart3',
    examples: ['Show engagement metrics'],
    keywords: ['track', 'engagement', 'metrics'],
  },
  {
    id: 'notification.schedule_followup',
    name: 'Schedule Follow-up',
    description: 'Schedule automatic follow-ups',
    category: 'automation',
    icon: 'Clock',
    examples: ['Schedule follow-up for next week'],
    keywords: ['schedule', 'follow-up'],
  },

  // ==========================================
  // SKIP TRACING (10 tools)
  // ==========================================
  {
    id: 'skip_trace.lookup',
    name: 'Skip Trace Owner',
    description: 'Get owner contact information',
    category: 'skip_tracing',
    icon: 'Phone',
    examples: ['Get contact info for this owner', "Find the owner's phone number"],
    keywords: ['skip trace', 'contact', 'phone'],
    isPrimary: true,
  },
  {
    id: 'skip_trace.batch_lookup',
    name: 'Batch Skip Trace',
    description: 'Skip trace multiple properties',
    category: 'skip_tracing',
    icon: 'Users',
    examples: ['Skip trace all properties in my list'],
    keywords: ['batch', 'skip trace', 'multiple'],
  },
  {
    id: 'skip_trace.find_owner',
    name: 'Find Owner',
    description: 'Find property owner contact',
    category: 'skip_tracing',
    icon: 'UserSearch',
    examples: ['Find the owner of this property'],
    keywords: ['find', 'owner', 'contact'],
  },
  {
    id: 'skip_trace.verify_contact',
    name: 'Verify Contact Info',
    description: 'Verify contact accuracy',
    category: 'skip_tracing',
    icon: 'CheckCircle',
    examples: ['Verify this phone number'],
    keywords: ['verify', 'contact', 'accuracy'],
  },
  {
    id: 'skip_trace.find_relatives',
    name: 'Find Owner Relatives',
    description: 'Find relatives and associates',
    category: 'skip_tracing',
    icon: 'Users',
    examples: ['Find relatives of this owner'],
    keywords: ['relatives', 'associates', 'family'],
  },
  {
    id: 'skip_trace.get_history',
    name: 'Contact History',
    description: 'Get historical contact information',
    category: 'skip_tracing',
    icon: 'Clock',
    examples: ['Show contact history for this owner'],
    keywords: ['history', 'contact', 'historical'],
  },
  {
    id: 'skip_trace.social_profiles',
    name: 'Find Social Profiles',
    description: 'Find social media profiles',
    category: 'skip_tracing',
    icon: 'Globe',
    examples: ['Find social profiles for this owner'],
    keywords: ['social', 'profiles', 'media'],
  },
  {
    id: 'skip_trace.email_validation',
    name: 'Validate Email',
    description: 'Validate email deliverability',
    category: 'skip_tracing',
    icon: 'Mail',
    examples: ['Validate this email address'],
    keywords: ['validate', 'email'],
  },
  {
    id: 'skip_trace.phone_validation',
    name: 'Validate Phone',
    description: 'Validate phone number',
    category: 'skip_tracing',
    icon: 'Phone',
    examples: ['Validate this phone number'],
    keywords: ['validate', 'phone'],
  },
  {
    id: 'skip_trace.lien_search',
    name: 'Search Liens',
    description: 'Search for liens and judgments',
    category: 'skip_tracing',
    icon: 'FileText',
    examples: ['Search liens on this property'],
    keywords: ['liens', 'judgments', 'search'],
  },

  // ==========================================
  // DEAL PIPELINE (12 tools)
  // ==========================================
  {
    id: 'pipeline.add_activity',
    name: 'Add to Pipeline',
    description: 'Move property into deal pipeline',
    category: 'deal_pipeline',
    icon: 'GitBranch',
    examples: ['Add this to my pipeline', 'Move this deal to Under Contract'],
    keywords: ['pipeline', 'deal', 'add'],
  },
  {
    id: 'pipeline.analyze_pipeline',
    name: 'Analyze Pipeline',
    description: 'Get pipeline insights',
    category: 'deal_pipeline',
    icon: 'BarChart3',
    examples: ["How's my pipeline looking?", 'What deals need attention?'],
    keywords: ['pipeline', 'analyze', 'insights'],
  },
  {
    id: 'deal.create',
    name: 'Create Deal',
    description: 'Create new deal',
    category: 'deal_pipeline',
    icon: 'Plus',
    examples: ['Create a new deal'],
    keywords: ['create', 'deal', 'new'],
  },
  {
    id: 'deal.update_stage',
    name: 'Update Deal Stage',
    description: 'Move deal to different stage',
    category: 'deal_pipeline',
    icon: 'ArrowRight',
    examples: ['Move this deal to closing'],
    keywords: ['update', 'stage', 'move'],
  },
  {
    id: 'deal.analyze_progress',
    name: 'Analyze Deal Progress',
    description: 'Analyze deal progress and bottlenecks',
    category: 'deal_pipeline',
    icon: 'Activity',
    examples: ['Why is this deal stalled?'],
    keywords: ['analyze', 'progress', 'bottleneck'],
  },
  {
    id: 'deal.generate_offer_strategy',
    name: 'Generate Offer Strategy',
    description: 'Calculate tiered offer prices',
    category: 'deal_pipeline',
    icon: 'Target',
    examples: ['Create an offer strategy'],
    keywords: ['offer', 'strategy', 'tiered'],
  },
  {
    id: 'deal.assign_buyer',
    name: 'Assign Buyer',
    description: 'Assign buyer to deal',
    category: 'deal_pipeline',
    icon: 'UserPlus',
    examples: ['Assign this buyer to the deal'],
    keywords: ['assign', 'buyer', 'deal'],
  },
  {
    id: 'deal.get_timeline',
    name: 'Deal Timeline',
    description: 'Get activity timeline',
    category: 'deal_pipeline',
    icon: 'Clock',
    examples: ['Show deal timeline'],
    keywords: ['timeline', 'activity', 'history'],
  },
  {
    id: 'deal.predict_outcome',
    name: 'Predict Deal Outcome',
    description: 'Predict closing likelihood',
    category: 'deal_pipeline',
    icon: 'Target',
    examples: ['Will this deal close?'],
    keywords: ['predict', 'outcome', 'close'],
    isAdvanced: true,
  },
  {
    id: 'deal.generate_summary',
    name: 'Generate Deal Summary',
    description: 'Create comprehensive deal summary',
    category: 'documents',
    icon: 'FileText',
    examples: ['Generate a deal summary'],
    keywords: ['summary', 'deal', 'report'],
  },
  {
    id: 'deal.flag_issues',
    name: 'Flag Deal Issues',
    description: 'Identify deals needing attention',
    category: 'deal_pipeline',
    icon: 'AlertTriangle',
    examples: ['Which deals need attention?', 'Show me stalled deals'],
    keywords: ['issues', 'flag', 'attention'],
  },
  {
    id: 'dashboard.funnel',
    name: 'Conversion Funnel',
    description: 'Analyze deal conversion funnel',
    category: 'deal_pipeline',
    icon: 'GitBranch',
    examples: ['Show me my conversion funnel', 'Where am I losing deals?'],
    keywords: ['funnel', 'conversion', 'analyze'],
  },

  // ==========================================
  // DOCUMENTS (6 tools)
  // ==========================================
  {
    id: 'docs.generate_offer_letter',
    name: 'Generate Offer Letter',
    description: 'Create property offer letter',
    category: 'documents',
    icon: 'FileText',
    examples: ['Create an offer letter for $150k'],
    keywords: ['offer', 'letter', 'document'],
    isPrimary: true,
  },
  {
    id: 'docs.generate_deal_summary',
    name: 'Generate Deal Summary',
    description: 'Create deal summary report',
    category: 'documents',
    icon: 'FileSpreadsheet',
    examples: ['Create a deal summary for this property'],
    keywords: ['summary', 'report', 'deal'],
  },
  {
    id: 'docs.generate_comp_report',
    name: 'Generate Comp Report',
    description: 'Generate comparable sales report',
    category: 'documents',
    icon: 'FileText',
    examples: ['Generate a comp report'],
    keywords: ['comp', 'report', 'comparables'],
  },

  // ==========================================
  // PERMITS (8 tools)
  // ==========================================
  {
    id: 'permit.history',
    name: 'Permit History',
    description: 'Get complete permit history',
    category: 'permits',
    icon: 'FileText',
    examples: ['Show permit history', 'Has this been renovated recently?'],
    keywords: ['permits', 'history', 'renovations'],
  },
  {
    id: 'permit.details',
    name: 'Permit Details',
    description: 'Get detailed permit information',
    category: 'permits',
    icon: 'FileText',
    examples: ['Show details for this permit'],
    keywords: ['permit', 'details', 'information'],
  },
  {
    id: 'permit.search',
    name: 'Search Permits',
    description: 'Search permits in area',
    category: 'permits',
    icon: 'Search',
    examples: ['Search permits in this neighborhood'],
    keywords: ['search', 'permits', 'area'],
  },
  {
    id: 'permit.metrics',
    name: 'Permit Metrics',
    description: 'Get aggregated permit metrics',
    category: 'permits',
    icon: 'BarChart3',
    examples: ['Show permit metrics for this property'],
    keywords: ['metrics', 'permits', 'statistics'],
  },
  {
    id: 'permit.check_system_age',
    name: 'Check System Age',
    description: 'Check age of major systems',
    category: 'permits',
    icon: 'Clock',
    examples: ['How old is the roof?'],
    keywords: ['age', 'systems', 'roof', 'hvac'],
  },
  {
    id: 'permit.deferred_maintenance',
    name: 'Identify Deferred Maintenance',
    description: 'Find properties with deferred maintenance',
    category: 'permits',
    icon: 'AlertTriangle',
    examples: ['Find properties with no recent permits'],
    keywords: ['deferred', 'maintenance', 'neglect'],
  },
  {
    id: 'permit.stalled',
    name: 'Find Stalled Permits',
    description: 'Find properties with stalled permits',
    category: 'permits',
    icon: 'Clock',
    examples: ['Find stalled permits in this area'],
    keywords: ['stalled', 'expired', 'permits'],
  },

  // ==========================================
  // CONTRACTORS (5 tools)
  // ==========================================
  {
    id: 'contractor.search',
    name: 'Find Contractors',
    description: 'Search contractors by location',
    category: 'contractors',
    icon: 'Hammer',
    examples: ['Find roofers in Tampa', 'Who are the best general contractors?'],
    keywords: ['contractors', 'find', 'search'],
  },
  {
    id: 'contractor.details',
    name: 'Contractor Details',
    description: 'Get contractor information',
    category: 'contractors',
    icon: 'FileText',
    examples: ['Tell me about this contractor'],
    keywords: ['contractor', 'details', 'info'],
  },
  {
    id: 'contractor.history',
    name: 'Contractor History',
    description: 'Get contractor permit history',
    category: 'contractors',
    icon: 'Clock',
    examples: ['Show permit history for this contractor'],
    keywords: ['contractor', 'history', 'permits'],
  },
  {
    id: 'contractor.compare',
    name: 'Compare Contractors',
    description: 'Compare multiple contractors',
    category: 'contractors',
    icon: 'GitCompare',
    examples: ['Compare these 3 contractors'],
    keywords: ['compare', 'contractors'],
  },
  {
    id: 'contractor.top',
    name: 'Top Contractors',
    description: 'Find highest-rated contractors',
    category: 'contractors',
    icon: 'Star',
    examples: ['Show top-rated contractors in Tampa'],
    keywords: ['top', 'best', 'rated', 'contractors'],
  },

  // ==========================================
  // CRM & LISTS (18 tools)
  // ==========================================
  {
    id: 'crm.add_note',
    name: 'Add Note',
    description: 'Add notes to properties or deals',
    category: 'crm',
    icon: 'StickyNote',
    examples: ['Add a note that owner is willing to negotiate'],
    keywords: ['note', 'add', 'memo'],
  },
  {
    id: 'crm.create_lead_list',
    name: 'Create Lead List',
    description: 'Create new lead list',
    category: 'crm',
    icon: 'Plus',
    examples: ['Create a new lead list'],
    keywords: ['create', 'list', 'leads'],
  },
  {
    id: 'crm.rank_by_motivation',
    name: 'Rank by Motivation',
    description: 'Sort leads by motivation score',
    category: 'crm',
    icon: 'Star',
    examples: ['Rank these leads by motivation'],
    keywords: ['rank', 'sort', 'motivation'],
  },
  {
    id: 'crm.suggest_outreach',
    name: 'Suggest Lead Outreach',
    description: 'Recommend leads to contact',
    category: 'crm',
    icon: 'Target',
    examples: ['Which leads should I contact?'],
    keywords: ['suggest', 'outreach', 'contact'],
  },
  {
    id: 'crm.analyze_source',
    name: 'Analyze Lead Source',
    description: 'Analyze performance of lead sources',
    category: 'crm',
    icon: 'BarChart3',
    examples: ['Which lead sources perform best?'],
    keywords: ['analyze', 'source', 'performance'],
  },
  {
    id: 'crm.segment_leads',
    name: 'Segment Leads',
    description: 'Group leads by criteria',
    category: 'crm',
    icon: 'Users',
    examples: ['Segment leads by motivation level'],
    keywords: ['segment', 'group', 'categorize'],
  },
  {
    id: 'predict.lead_score',
    name: 'Lead Scoring',
    description: 'Score and prioritize leads',
    category: 'crm',
    icon: 'Star',
    examples: ['Score these leads for me', 'Which leads should I focus on first?'],
    keywords: ['score', 'prioritize', 'rank'],
  },
  {
    id: 'crm.generate_report',
    name: 'Generate Lead Report',
    description: 'Create lead summary report',
    category: 'crm',
    icon: 'FileText',
    examples: ['Generate a lead report'],
    keywords: ['report', 'leads', 'summary'],
  },
  {
    id: 'crm.identify_hot',
    name: 'Hot Leads',
    description: 'Find your hottest leads',
    category: 'crm',
    icon: 'Flame',
    examples: ['Show me my hottest leads', 'Who should I call today?'],
    keywords: ['hot', 'leads', 'priority'],
  },
  {
    id: 'crm.track_engagement',
    name: 'Track Lead Engagement',
    description: 'Track engagement history',
    category: 'crm',
    icon: 'Activity',
    examples: ['Show engagement history for this lead'],
    keywords: ['track', 'engagement', 'history'],
  },
  {
    id: 'crm.suggest_nurturing',
    name: 'Suggest Lead Nurturing',
    description: 'Get nurturing plan suggestions',
    category: 'crm',
    icon: 'Sparkles',
    examples: ['How should I nurture this lead?'],
    keywords: ['nurture', 'plan', 'suggestions'],
  },
  {
    id: 'crm.merge_leads',
    name: 'Merge Leads',
    description: 'Merge duplicate lead records',
    category: 'crm',
    icon: 'Merge',
    examples: ['Merge these duplicate leads'],
    keywords: ['merge', 'duplicate', 'combine'],
  },
  {
    id: 'crm.export_leads',
    name: 'Export Leads',
    description: 'Export lead data',
    category: 'crm',
    icon: 'Download',
    examples: ['Export leads to CSV'],
    keywords: ['export', 'download', 'leads'],
  },
  {
    id: 'crm.predict_conversion',
    name: 'Predict Lead Conversion',
    description: 'Predict lead conversion likelihood',
    category: 'predictive',
    icon: 'Target',
    examples: ['Will this lead convert?'],
    keywords: ['predict', 'conversion', 'likelihood'],
    isAdvanced: true,
  },

  // ==========================================
  // AUTOMATION (5 tools)
  // ==========================================
  {
    id: 'workflow.auto_follow_up',
    name: 'Auto Follow-Up',
    description: 'Set up automated follow-up sequences',
    category: 'automation',
    icon: 'Zap',
    examples: ['Set up auto follow-up for stalled deals'],
    keywords: ['automation', 'follow-up', 'workflow'],
  },
  {
    id: 'workflow.alert_on_match',
    name: 'Property Alerts',
    description: 'Get notified when properties match criteria',
    category: 'automation',
    icon: 'Bell',
    examples: ['Alert me when 3 beds under $200k come on market'],
    keywords: ['alert', 'notify', 'match'],
  },
  {
    id: 'workflow.deal_stage_trigger',
    name: 'Deal Stage Trigger',
    description: 'Create automated actions for stage changes',
    category: 'automation',
    icon: 'GitBranch',
    examples: ['Automatically notify buyer when deal reaches Under Contract'],
    keywords: ['trigger', 'stage', 'automated'],
  },

  // ==========================================
  // MAP TOOLS (6 tools)
  // ==========================================
  {
    id: 'map.compare_areas',
    name: 'Compare Geographic Areas',
    description: 'Compare multiple areas side-by-side',
    category: 'map_tools',
    icon: 'GitCompare',
    examples: ['Compare downtown Tampa vs South Tampa'],
    keywords: ['compare', 'areas', 'geographic'],
  },
  {
    id: 'map.toggle_style',
    name: 'Toggle Map Style',
    description: 'Switch map visual styles',
    category: 'map_tools',
    icon: 'Map',
    examples: ['Switch to satellite view'],
    keywords: ['map', 'style', 'view'],
  },
  {
    id: 'map.spatial_query',
    name: 'Spatial Query',
    description: 'Query points of interest near location',
    category: 'map_tools',
    icon: 'MapPin',
    examples: ['Show schools near this property'],
    keywords: ['spatial', 'query', 'poi'],
  },
  {
    id: 'map.compare_neighborhoods',
    name: 'Compare Neighborhoods',
    description: 'Compare neighborhoods by livability factors',
    category: 'map_tools',
    icon: 'GitCompare',
    examples: ['Compare neighborhoods in Tampa'],
    keywords: ['compare', 'neighborhoods', 'livability'],
  },
  {
    id: 'census.get_geography',
    name: 'Get Census Geography',
    description: 'Get Census geographic identifiers',
    category: 'map_tools',
    icon: 'MapPin',
    examples: ['What Census tract is this in?'],
    keywords: ['census', 'geography', 'tract'],
  },
  {
    id: 'census.get_boundary_polygon',
    name: 'Get Census Boundary',
    description: 'Get Census boundary polygons',
    category: 'map_tools',
    icon: 'Map',
    examples: ['Show Census tract boundary'],
    keywords: ['census', 'boundary', 'polygon'],
  },

  // ==========================================
  // INTELLIGENCE (3 tools)
  // ==========================================
  {
    id: 'intel.competitor_activity',
    name: 'Competitor Analysis',
    description: 'Analyze investor activity',
    category: 'intelligence',
    icon: 'Users',
    examples: ['What are other investors doing in Tampa?', 'Show me where flippers are buying'],
    keywords: ['competitor', 'investor', 'activity'],
    isAdvanced: true,
  },
  {
    id: 'intel.market_saturation',
    name: 'Market Saturation Analysis',
    description: 'Check if market is oversaturated',
    category: 'intelligence',
    icon: 'Activity',
    examples: ['Is the Tampa market oversaturated?'],
    keywords: ['saturation', 'competition', 'crowded'],
    isAdvanced: true,
  },
  {
    id: 'intel.market_velocity',
    name: 'Market Velocity Analysis',
    description: 'Comprehensive market velocity analysis',
    category: 'intelligence',
    icon: 'Gauge',
    examples: ['Analyze market velocity for investment timing'],
    keywords: ['velocity', 'timing', 'market'],
  },

  // ==========================================
  // BATCH OPERATIONS (4 tools)
  // ==========================================
  {
    id: 'batch.skip_trace_bulk',
    name: 'Bulk Skip Trace',
    description: 'Skip trace multiple properties at once',
    category: 'batch_operations',
    icon: 'Users',
    examples: ['Skip trace all 50 properties in this list'],
    keywords: ['bulk', 'batch', 'skip trace'],
  },
  {
    id: 'batch.add_to_list_bulk',
    name: 'Bulk Add to List',
    description: 'Add multiple properties to list',
    category: 'batch_operations',
    icon: 'ListPlus',
    examples: ['Add all these properties to my hot leads list'],
    keywords: ['bulk', 'add', 'list'],
  },
  {
    id: 'batch.update_deal_status',
    name: 'Bulk Update Deal Status',
    description: 'Update status of multiple deals',
    category: 'batch_operations',
    icon: 'Edit',
    examples: ['Mark all these deals as qualified'],
    keywords: ['bulk', 'update', 'status'],
  },
  {
    id: 'batch.export_properties',
    name: 'Export Properties',
    description: 'Export property data to CSV/Excel',
    category: 'batch_operations',
    icon: 'Download',
    examples: ['Export these properties to Excel', 'Download this list as CSV'],
    keywords: ['export', 'download', 'csv', 'excel'],
  },

  // ==========================================
  // ANALYTICS & REPORTING (12 tools)
  // ==========================================
  {
    id: 'dashboard.insights',
    name: 'Dashboard Insights',
    description: 'Get AI-powered insights',
    category: 'reporting',
    icon: 'Sparkles',
    examples: ['What insights do you have for me?', 'How am I performing this month?'],
    keywords: ['insights', 'dashboard', 'performance'],
  },
  {
    id: 'dashboard.goals',
    name: 'Goal Tracking',
    description: 'Track progress towards goals',
    category: 'reporting',
    icon: 'Target',
    examples: ['Am I on track to hit my goals?'],
    keywords: ['goals', 'tracking', 'progress'],
  },
  {
    id: 'dashboard.performance',
    name: 'Performance Summary',
    description: 'Get performance metrics summary',
    category: 'reporting',
    icon: 'BarChart3',
    examples: ['Show my performance summary'],
    keywords: ['performance', 'summary', 'metrics'],
  },
  {
    id: 'dashboard.report',
    name: 'Generate Report',
    description: 'Generate automated analytics reports',
    category: 'reporting',
    icon: 'FileText',
    examples: ['Generate a monthly report'],
    keywords: ['report', 'analytics', 'generate'],
  },
  {
    id: 'dashboard.anomalies',
    name: 'Anomaly Detection',
    description: 'Detect unusual patterns',
    category: 'reporting',
    icon: 'AlertTriangle',
    examples: ['Detect anomalies in my metrics'],
    keywords: ['anomaly', 'unusual', 'patterns'],
    isAdvanced: true,
  },
  {
    id: 'dashboard.trends',
    name: 'Dashboard Trends',
    description: 'Analyze trends across metrics',
    category: 'reporting',
    icon: 'TrendingUp',
    examples: ['Show trends in my key metrics'],
    keywords: ['trends', 'analysis', 'metrics'],
  },
  {
    id: 'dashboard.activity',
    name: 'Activity Summary',
    description: 'Summarize recent activity',
    category: 'reporting',
    icon: 'Activity',
    examples: ['Summarize my recent activity'],
    keywords: ['activity', 'summary', 'recent'],
  },
  {
    id: 'dashboard.compare_periods',
    name: 'Compare Periods',
    description: 'Compare metrics between time periods',
    category: 'reporting',
    icon: 'GitCompare',
    examples: ['Compare this month to last month'],
    keywords: ['compare', 'periods', 'time'],
  },
  {
    id: 'dashboard.alerts',
    name: 'Get Alerts',
    description: 'Get current alerts and notifications',
    category: 'reporting',
    icon: 'Bell',
    examples: ['Show my alerts'],
    keywords: ['alerts', 'notifications'],
  },
  {
    id: 'dashboard.recommendations',
    name: 'Get Recommendations',
    description: 'Get AI-powered action recommendations',
    category: 'reporting',
    icon: 'Sparkles',
    examples: ['What should I focus on?'],
    keywords: ['recommendations', 'suggestions', 'actions'],
  },
  {
    id: 'dashboard.kpis',
    name: 'KPI Status',
    description: 'Get current KPI status',
    category: 'reporting',
    icon: 'BarChart3',
    examples: ['Show KPI status'],
    keywords: ['kpi', 'status', 'metrics'],
  },

  // ==========================================
  // PORTFOLIO MANAGEMENT (3 tools)
  // ==========================================
  {
    id: 'portfolio.get_summary',
    name: 'Portfolio Summary',
    description: 'Get summary of your portfolio',
    category: 'portfolio',
    icon: 'Home',
    examples: ['Show my portfolio summary'],
    keywords: ['portfolio', 'summary', 'overview'],
  },
  {
    id: 'portfolio.analyze_performance',
    name: 'Portfolio Performance',
    description: 'Analyze portfolio performance',
    category: 'portfolio',
    icon: 'TrendingUp',
    examples: ['Analyze my portfolio performance'],
    keywords: ['portfolio', 'performance', 'analysis'],
  },
  {
    id: 'portfolio.compare_properties',
    name: 'Compare Portfolio Properties',
    description: 'Compare properties in portfolio',
    category: 'portfolio',
    icon: 'GitCompare',
    examples: ['Compare properties in my portfolio'],
    keywords: ['compare', 'portfolio', 'properties'],
  },

  // ==========================================
  // INTEGRATIONS (2 tools)
  // ==========================================
  {
    id: 'sync.crm_export',
    name: 'Export to CRM',
    description: 'Export data to external CRM',
    category: 'integrations',
    icon: 'Upload',
    examples: ['Export these leads to my CRM'],
    keywords: ['export', 'crm', 'sync'],
    isAdvanced: true,
  },
  {
    id: 'sync.calendar_integration',
    name: 'Calendar Integration',
    description: 'Manage calendar events',
    category: 'integrations',
    icon: 'Calendar',
    examples: ['Add property viewing to my calendar'],
    keywords: ['calendar', 'schedule', 'integration'],
  },

  // ==========================================
  // VERTICALS (4 tools)
  // ==========================================
  {
    id: 'vertical.get_active',
    name: 'Get Active Vertical',
    description: 'Get currently active business vertical',
    category: 'verticals',
    icon: 'Settings',
    examples: ['What vertical am I in?'],
    keywords: ['vertical', 'active', 'current'],
  },
  {
    id: 'vertical.switch',
    name: 'Switch Vertical',
    description: 'Switch business vertical',
    category: 'verticals',
    icon: 'RefreshCw',
    examples: ['Switch to wholesaling vertical'],
    keywords: ['switch', 'vertical', 'change'],
  },
  {
    id: 'vertical.filters',
    name: 'Get Vertical Filters',
    description: 'Get filters for a vertical',
    category: 'verticals',
    icon: 'Filter',
    examples: ['Show filters for this vertical'],
    keywords: ['filters', 'vertical'],
  },
  {
    id: 'vertical.insights',
    name: 'Vertical Insights',
    description: 'Get vertical-specific insights',
    category: 'verticals',
    icon: 'Sparkles',
    examples: ['Give me insights for wholesaling'],
    keywords: ['insights', 'vertical', 'specific'],
  },

  // ==========================================
  // UTILITY TOOLS (4 tools)
  // ==========================================
  {
    id: 'utility.calculate_distance',
    name: 'Calculate Distance',
    description: 'Calculate distance between properties',
    category: 'map_tools',
    icon: 'Ruler',
    examples: ['How far is this from downtown?'],
    keywords: ['distance', 'calculate', 'measure'],
  },
  {
    id: 'utility.geocode_address',
    name: 'Geocode Address',
    description: 'Convert address to coordinates',
    category: 'map_tools',
    icon: 'MapPin',
    examples: ['Get coordinates for this address'],
    keywords: ['geocode', 'coordinates', 'address'],
  },
  {
    id: 'utility.reverse_geocode',
    name: 'Reverse Geocode',
    description: 'Convert coordinates to address',
    category: 'map_tools',
    icon: 'MapPin',
    examples: ['What address is at these coordinates?'],
    keywords: ['reverse', 'geocode', 'address'],
  },
  {
    id: 'utility.validate_address',
    name: 'Validate Address',
    description: 'Validate and standardize address',
    category: 'map_tools',
    icon: 'CheckCircle',
    examples: ['Validate this address'],
    keywords: ['validate', 'address', 'standardize'],
  },
];
